In [1]:
import numpy as np
import time as t

In [6]:
a = np.zeros(4); print(f'a vector a: {a} of shape: {a.shape} and datatype: {a.dtype}')
a = np.zeros(4,); print(f'a vector a: {a} of shape: {a.shape} and datatype: {a.dtype}')
a = np.random.random_sample(4); print(f'a vector a: {a} of shape: {a.shape} and datatype: {a.dtype}')

a vector a: [0. 0. 0. 0.] of shape: (4,) and datatype: float64
a vector a: [0. 0. 0. 0.] of shape: (4,) and datatype: float64
a vector a: [0.06498611 0.74317741 0.93962277 0.7700356 ] of shape: (4,) and datatype: float64


In [9]:
a = np.arange(4.); print(f'a vector a: {a} of shape: {a.shape} and datatype: {a.dtype}')
a = np.random.rand(4); print(f'a vector a: {a} of shape: {a.shape} and datatype: {a.dtype}')

a vector a: [0. 1. 2. 3.] of shape: (4,) and datatype: float64
a vector a: [0.06392876 0.82759495 0.40112686 0.54797739] of shape: (4,) and datatype: float64


In [10]:
a = np.array([5,4,3,2,1]); print(f'a vector a: {a} of shape: {a.shape} and datatype: {a.dtype}')
a = np.array([5.,4,3,2,1]); print(f'a vector a: {a} of shape: {a.shape} and datatype: {a.dtype}')

a vector a: [5 4 3 2 1] of shape: (5,) and datatype: int32
a vector a: [5. 4. 3. 2. 1.] of shape: (5,) and datatype: float64


In [19]:
a = np.arange(10)
print(a)
c = a[2:7:1]; print(c)
c = a[2:7:2]; print(c)
c = a[:]; print(c)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]
[0 1 2 3 4 5 6 7 8 9]


In [20]:
a = np.array([1,2,3,4])
b = np.sum(a); print(b)
b = np.mean(a); print(b)
b = -a; print(b)
b = a**2; print(b)

10
2.5
[-1 -2 -3 -4]
[ 1  4  9 16]


In [24]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])
c = a*b; print(c)
d = 5*a; print(d)
p = np.dot(a,b); print(p)

[-1 -4  9 16]
[ 5 10 15 20]
20


In [30]:
a = np.zeros((2,5)); print(f'a vector a: {a} of shape: {a.shape} and datatype: {a.dtype}')
a = np.zeros((5,2)); print(f'a vector a: {a} of shape: {a.shape} and datatype: {a.dtype}')
a = np.random.random_sample((5,2)); print(f'a vector a: {a} of shape: {a.shape} and datatype: {a.dtype}')

a vector a: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] of shape: (2, 5) and datatype: float64
a vector a: [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] of shape: (5, 2) and datatype: float64
a vector a: [[0.35856928 0.92963368]
 [0.67798376 0.58534813]
 [0.22703874 0.28433979]
 [0.74349216 0.04554662]
 [0.14828986 0.53012933]] of shape: (5, 2) and datatype: float64


In [33]:
a = np.array(([5,2],[3,1],[2,3])); print(f'a vector a: {a} of shape: {a.shape} and datatype: {a.dtype}')

a vector a: [[5 2]
 [3 1]
 [2 3]] of shape: (3, 2) and datatype: int32


In [43]:
a = np.arange(8).reshape(2, 4)   
print(f"a.shape: {a.shape}, \na= {a}")

a.shape: (2, 4), 
a= [[0 1 2 3]
 [4 5 6 7]]
